# Apply settings to the whole workspace
workspace = true

# General settings - only for version bumping, GitHub workflow handles the rest
consolidate-commits = true
push = false                  # We handle pushing in GitHub workflow
tag = false                   # We handle tagging in GitHub workflow
publish = false               # We handle publishing in GitHub workflow
allow-branch = ["main"]
dependent-version = "upgrade" # upgrade version for dependent crates

[release]
update-workspace-dependencies = true
